micronaut:
  application:
    name: mnStockBroker
  server:
    port: 8081
hello:
  controller:
    path: "/hello"
  service:
    greeting: "Hello from service"
  config:
    greeting:
      en: "Hi babe!"
      per: "سلام گوگولی!"
      de: "Hallo!"